from api.views.user import *
from api.views.company import *
from api.views.related_company_user import *
from api.views.school import *
from api.views.related_school_user import *
from api.views.yetenek import *
from api.views.aday_deneyimleri import *
from api.views.aday import *
from api.views.related_aday_yetenek import *